### ISSUE TITLE
[Bug]: bad handling of quotes in `snapcraft-args`

### ISSUE THREAD

**Issue by Saviq** [diddlesnaps/snapcraft-multiarch-action#20]
### What happened?

As I was moving from bash to this action, I had quotes around one of the arguments. Snapcraft failed to run, then, because the quotes were escaped:

```
Run diddlesnaps/snapcraft-multiarch-action@v1
  with:
    store-auth: ***
    snapcraft-channel: stable
    architecture: amd64
    snapcraft-args: push glvnd-core22_0.01_amd64.snap --release 'edge/pr1'
    path: .
    use-podman: false
    build-info: true
# ...
Executing: 'snap run snapcraft push glvnd-core22_0.01_amd64.snap --release \'edge/pr1\' '
Uploading... (--->)
Uploading... (<---)
craft-store error: Store operation failed:
- invalid-field: No valid risk provided: 'edge, pr1'
```

https://github.com/MirServer/glvnd-core22/actions/runs/4341495156/jobs/7581165120#step:3:1586

### What should have happened?

Need a way to quote arguments in `snapcraft-args`. It may be best if it's actually a list, rather than a string.

### Output of `snap info $snap_name`

```shell
N/A
```

### Output of `snap connections $snap_name`

```shell
N/A
```

### Output of `snap version`

```shell
N/A
```
